import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavigationProgress from "@/app/shared/NavigationProgress";
import UserStatusTracker from "@/app/shared/UserStatusTracker";
import MessagePopupWrapper from "@/app/shared/MessagePopupWrapper";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import MaintenanceGuard from "@/app/shared/MaintenanceGuard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Teachers Desk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <head>
        <link href="https://fonts.cdnfonts.com/css/life-lt-roman" rel="stylesheet" />
        <link href="https://fonts.cdnfonts.com/css/br-cobane" rel="stylesheet" />
        <link href="https://fonts.cdnfonts.com/css/oswald-4" rel="stylesheet" />
      </head>
      <body
        className="antialiased bg-[#eeeeee] h-full"
      >
        {/* Global navigation progress bar — visible on every route change */}
        <NavigationProgress />
        <UserStatusTracker />
        <MessagePopupWrapper />
        <ToastContainer position="top-right" autoClose={3000} hideProgressBar={false} closeOnClick pauseOnHover draggable />
        <MaintenanceGuard>
          {children}
        </MaintenanceGuard>
      </body>
    </html>
  );
}
